### ISSUE TITLE
Add supported devices section to README.md

### ISSUE THREAD

**Issue by timmkrause** [tasmota/tasmotizer#102]
Background: I am completely new to the ESP* and self-made home automation scene and just starting with it.

I stumbled upon the difference between ESP32 and ESP8266 and ordered the "new kid on the block", the ESP32.

Tasmota seems to support as beta and because Tasmotizer has many advantages and makes things so much easier, I gave it a shot, also because it claims that it is the "The full-featured flashing tool for Tasmota.".

But it seems that Tasmotizer does not support ESP32. There is no `tasmota32` selectable in the dropdown lists and if downloaded and selected manually, it can't connect.

Maybe it's just beneficial to beginners (that decision is up to you), but what do you think about adapting the readme regarding ESP8266 only (?) support?
In #75 I saw a comment that ESP32 support is in the making, but I think even until then it can potentially help a few people.

Looking forward to your answers & opinions.

**Comment by Jason2866** [comment]
Thx, info added
