### ISSUE TITLE
Wrong sensor 

### ISSUE THREAD

**Issue by Kedryn** [tasmota/tasmotizer#107]
I've loaded up Tasmota-sensor 9.4.0 via Tasmotizer to my nodemcu.
I've connected an AHT10 (hum/temp) via I2C but it's detected as VEML6070 (UV light sensor)

**Comment by ascillato** [comment]
Hi, your issue is not related to Tasmotizer. As there are sensors with the same I2C address, you need to disable and enable drivers to choose the one you need. Please check `i2cdriver` command. If you need further assistance , please address this to the Tasmota support chat. Thanks.
