### ISSUE TITLE
Feature Request: Use IP instead of com port

### ISSUE THREAD

**Issue by jeroenst** [tasmota/tasmotizer#109]
I have a lot of devices flashed with arduino-ota which I want to change to tasmota.

It would be helpful if tasmotized also detects ip's of devices supporting arduino ota:

https://github.com/esp8266/Arduino/blob/master/tools/espota.py

**Comment by jeroenst** [comment]
I tried to flash tasmota-minimal.bin with espota.py, but it bricked my device unfortunately.

So I have to serial flash it again

**Comment by Jason2866** [comment]
Not possible. Initial flashing of Tasmota has to be done always via serial.
You can not upgrade to Tasmota from a other firmware via Arduino-OTA.
