### ISSUE TITLE
How to send config

### ISSUE THREAD

**Issue by rebel7580** [tasmota/tasmotizer#11]
I programmed a device successfully, then tried to use the "Send Config" option.  What I got was a grayed out screen with no way to enter any info to it. I suppose I'm doing something wrong, but not sure what.
![taz](https://user-images.githubusercontent.com/30353207/71548919-37181080-2983-11ea-9ad7-db6fefccd4ba.gif)

![config](https://user-images.githubusercontent.com/30353207/71548920-3a130100-2983-11ea-9427-98b494811b3c.gif)

With this screen when I click "save" it attempts to upload the default config to the device.

**Comment by jziolkowski** [comment]
You must first click the box near the section you want to configure. Then that section will be enabled for input.

**Comment by rebel7580** [comment]
Ah. With that dark theme, I didn't even see the check boxes! :)
Thanks.
