### ISSUE TITLE
Compile for BK7231T (WB2S, WB3S, etc) 

### ISSUE THREAD

**Issue by spacelama** [tasmota/tasmotizer#124]
Looks like someone has finally managed to compile something for the the BK7231T (WB2S, WB3S etc), so it would be wonderful to see Tasmota ported to compiling for that target.

Perhaps something is able to be based off the work here (for those of us who want the full features that Tasmota supplies, rather than openshwprojects's more pared back offering):
https://www.reddit.com/r/tasmota/comments/sez4ho/tasmota_replacement_for_bk7231t_wb2s_wb3s_etc/

**Comment by Jason2866** [comment]
Tasmota will not be available on this chip. So Tasmotizer will not support
