### ISSUE TITLE
Cannot select a serial port

### ISSUE THREAD

**Issue by fgordon** [tasmota/tasmotizer#126]
After the installation via the AUR (git), just like after the installation with pip3, I can't select a serial port in the GUI. nothing is visible in the selection. the corresponding user is in the group tty. im on arch btw ;-)

**Comment by jziolkowski** [comment]
check if you don't have to be in the `serial` group. Check if the USB adapter is visible in /dev/

**Comment by fgordon** [comment]
`id` print for my standarduser: 
....`5(tty)` ... `14(uucp)` ... 
Arch doesn't use `serial`. both of the above should be enough for the program to work correctly. 
by the way, there is also no port selection when i am logged in as root.

**Comment by fgordon** [comment]
`dmesg | grep tty` show something with 
`usb 3-2: usbfs: interface 0 claimed by ch341 while 'brltty' sets config #1` 
and
`ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0` 
so its a problem with brltty. i dont need it so a simple `pacman -R brltty` solve the issue.
