### ISSUE TITLE
Tasmotizer does not recognize FT232 after connecting Sonoff 4CH Pro R3

### ISSUE THREAD

**Issue by steef12111** [tasmota/tasmotizer#139]
Hi all,

Recently I got a Sonoff 4CH Pro R3 and FT232 serial to USB adapter. My goal was to flash the Sonoff device with Tasmota, following this guide, https://notenoughtech.com/sonoff/flashing-tasmota-on-4ch-r3-4chpro-r3/

When I try to connect my FT232, without the Sonoff device, to my laptop or pc (tried Windows and Ubuntu) it is recognized in the Device manager and Tasmotizer. Whenever I connect the Sonoff device I hear the tune of an USB being unplugged and the FT232 is nowhere to be found anymore, which makes that I am not able to flash my device.

Does anyone know what could be the cause of this and how it can be resolved? Many thanks in advance!

Setup where the FT232 is not recognized.
![Setup where the FT232 is not recognized](https://github.com/tasmota/tasmotizer/assets/46138546/758f929e-a80c-4720-b0cc-f9756eb945b3)

Setup where the FT232 is recognized
![Setup where the FT232 is recognized](https://github.com/tasmota/tasmotizer/assets/46138546/0b3e82bd-539d-4891-8be3-904a4af2eae1)

**Comment by Jason2866** [comment]
ft232 is not recommended for flashing esp
