### ISSUE TITLE
Error at programming Tasmota

### ISSUE THREAD

**Issue by Rudi-Ment** [tasmota/tasmotizer#16]
Hi. 

I try to programm a nodeMCU with ESP32 with the Tasmota.bin oder Tasmota-sensors.bin
The following message pops up in Tasmotizer:
a fatal error occurred invalid head of packet 0x46
Did anyone has an idea for this ?
Greatings
Rüdiger

**Comment by jziolkowski** [comment]
Tasmota doesn't support ESP32.

**Comment by eku** [comment]
> Tasmota doesn't support ESP32.

Well, that's no longer true. Are you going to support ESP32 in the future?

**Comment by hamwong** [comment]
hi, Tasmota have support esp32 now, will you support esp32 in near future?
