### ISSUE TITLE
Doesn't show tty USB on Mac with Catalina

### ISSUE THREAD

**Issue by Stooovie** [tasmota/tasmotizer#17]
tty USB is not offered in Tasmotizer under Catalina, even when the UART adapter is showing in System Information. Not even when run as sudo.

**Comment by Jason2866** [comment]
Sorry to hear. We cant help since we dont have Mac

**Comment by jziolkowski** [comment]
All I can suggest is please come to the Tasmota discord server and try asking if Mac users can provide some help.
