### ISSUE TITLE
crashes after clicking Tasmotize!

### ISSUE THREAD

**Issue by mbravorus** [tasmota/tasmotizer#2]
Installed with pip3 on a mac (OS X Mojave 10.14.6)

After setting the port and release binary crashes with

```
Traceback (most recent call last):
  File "/usr/local/bin/tasmotizer.py", line 657, in start_process
    dlg = FlashingDialog(self)
  File "/usr/local/bin/tasmotizer.py", line 303, in __init__
    esptool.sw.read_start.connect(self.read_start)
AttributeError: module 'esptool' has no attribute 'sw'
Abort trap: 6
```

esptool.py is verified as working (I used it to flash after reproducing the crash several times)

pyserial verified to be v3.4

**Comment by jziolkowski** [comment]
Can you uninstall esptool and check again? I suspect Python import the packaged esptool instead of the one modified provided by Tasmotizer.

**Comment by mbravorus** [comment]
I'll try that on the next device I tasmotize (next week) and report

but realistically, most people who are going to install tasmotizer will have esptool already installed, so it might be a good idea to document this at a minimum, and maybe work around it somehow, in the general spirit of magic tasmotization :)

**Comment by namadori** [comment]
I confirm your suspect, uninstalling esptool and reinstalling tasmotizer avoided the error.

**Comment by jziolkowski** [comment]
Thank you. I'll have to add it to 1.1 so it forces loading of the current .py file.

**Comment by mbravorus** [comment]
I also confirm that reinstallation after removing esptool works as described.

It's not very convenient though (because I sometimes need just the esptool, say, to quickly do a read_mac or something), so new solution in 1.1 will be great! Current workaround is to keep tasmotizer (or esptool) in a virtualenv.

**Comment by jziolkowski** [comment]
I've created a new branch (dev-1.1) with renamed esptool to enforce local import if esptool is present in python installation. Please test.

**Comment by jziolkowski** [comment]
the changes are now merged and released.
