### ISSUE TITLE
Error during execution after clone install

### ISSUE THREAD

**Issue by SamuelCarson** [tasmota/tasmotizer#27]
pi@raspberrypi:~/Downloads/tasmotizer $ python3 tasmotizer.py
libEGL warning: DRI2: failed to authenticate
qt5ct: using qt5ct plugin
qt5ct: palette support is disabled
qt5ct: custom style sheet is disabled

**Comment by SamuelCarson** [comment]
Flash works but in "send config"  no fields are writable
Raspian Buster 2020-02-13 with all updates

**Comment by Jason2866** [comment]
Have you tried to start with `sudo` ?
QT5 installed?

**Comment by SamuelCarson** [comment]
Yes to all

**Comment by jziolkowski** [comment]
You have to tick the small checkboxes next to group name, it enables them for editing and selects them to be sent to device.

**Comment by Jason2866** [comment]
See https://github.com/tasmota/tasmotizer/issues/26#issuecomment-672277551
