### ISSUE TITLE
Backup size for shelly devices should be 2MB

### ISSUE THREAD

**Issue by cflurin** [tasmota/tasmotizer#28]
Hi,

The backup size  should be variable. Shelly has a 2MB flash size.

Note: I had to clone the firmware from a new shelly 2.5 using esptool.py and restore it to the other shelly device.

**Comment by jziolkowski** [comment]
I'll have a look, this is certainly a needed feature.

**Comment by jziolkowski** [comment]
Please have a look at the 1.1d branch (to be released this week). I've added selectable backup size.

**Comment by Jason2866** [comment]
New build ready for testing https://github.com/tasmota/tasmotizer/tree/1.1d
Just some minor polish missing ...

**Comment by Jason2866** [comment]
Feature added in v.1.2
