### ISSUE TITLE
Exe file - differences between tasmotiozer.exe and tasmotizer-x86.exe file

### ISSUE THREAD

**Issue by bovirus** [tasmota/tasmotizer#32]
@jziolkowski

What are the differences between tasmotizer.exe and tasmotizer-x86.exe?

Could include this info in readme?

Thanks.

**Comment by Jason2866** [comment]
X86 and x64 version

**Comment by bovirus** [comment]
@jziolkowski 

tasmotizer.exe = x64 version
tasmotizer_x86.xe = x86 version

Then why don't rename 

**_tasmotizer.exe_** as **_tastnotizer_x64.exe_** 

to highlight these difference.

Please add this info about exe difference in readme.

Thanks.

**Comment by Jason2866** [comment]
Because x64 is standard these days

**Comment by bovirus** [comment]
@Jason2866 

I will avoid misunderstanding (not all user can understand that x64 is standard exe) and I will rename the exe as _x64.exe.

**Comment by ramanraja** [comment]
@Jason2866 is correct. I spent considerable time speculating the difference between these two versions. We work with low power, small footprint micro controllers, so X86 is still the norm in our organization. Ideally, the two versions should be named Tasmotizer_32_bit.exe and Tasmotizer_64_bit.exe.

**Comment by jziolkowski** [comment]
For some users their standard is X86, for others it's x64. I'm from the latter.
The version will be named as they are now. I've updated the readme.

Case closed.

**Comment by ramanraja** [comment]
OK, thank you.
(And thanks for this wonderful software. We all love it!)
Warm regards,
Rajaraman
