### ISSUE TITLE
New version of Magic Home - Tasmotizer can't connect

### ISSUE THREAD

**Issue by Mies84** [tasmota/tasmotizer#41]
The chip inside the new LED controllers from Magic Home is changed from ESP to probably Suzhou SmartChip Semiconductor Co., LTD. This one cannot be programmed by Tasmotizer. The pinout seemed to be the same. However the resitance is different. The Tasmotizer doesn't connect at all to the new chip.

![chip](https://user-images.githubusercontent.com/64786141/80973826-2b03fa00-8e20-11ea-998a-bfd31d5352e2.png)
![IMG_1956](https://user-images.githubusercontent.com/64786141/80973830-2b9c9080-8e20-11ea-9f43-ec35f2509bf5.JPG)
![IMG_1959](https://user-images.githubusercontent.com/64786141/80973832-2ccdbd80-8e20-11ea-96b3-f0ff344898d6.JPG)
![IMG_1960](https://user-images.githubusercontent.com/64786141/80973839-2d665400-8e20-11ea-9712-11467093b57e.JPG)
![IMG_1961](https://user-images.githubusercontent.com/64786141/80973840-2d665400-8e20-11ea-8847-037d6feaa99b.JPG)

**Comment by jziolkowski** [comment]
This device is not supported by Tasmota, so neither by Tasmotizer
