### ISSUE TITLE
Don't upgrade

### ISSUE THREAD

**Issue by fmarzocca** [tasmota/tasmotizer#49]
By using:

`pip3 install --upgrade tasmotizer`

it does not install latest version 1.1c

**Comment by Jason2866** [comment]
The pip version is not yet done. @faziaty does maintain this.
In the meantime please install as described in the readme of branch ota.tasmota

**Comment by fmarzocca** [comment]
Thanks. Do you know when the pip version will be ready?

**Comment by Jason2866** [comment]
I had no contact to @jziolkowski  So, sorry i cant tell you.

**Comment by fmarzocca** [comment]
Ok. Thanks
