### ISSUE TITLE
Flashing of Tasmota which is compiled for device with 4MB Flash usage is not working proper [used Tasmotizer 1.1c]

### ISSUE THREAD

**Issue by userTomK** [tasmota/tasmotizer#51]
Hello, 
I have WEMOS D1 mini R2 which has 4MB of Flash.
I compiled the TASMOTA Firmware with the following settings.

[platformio_override.ini]
[common]
board_build.ldscript      = eagle.flash.4m2m.ld

[user_config_override.h]
//Enable USAGE of the 4MB Flash of the Wemos D1 R2
#ifndef USE_SCRIPT_FATFS
#define USE_SCRIPT_FATFS -1
#endif
#ifndef FAT_SCRIPT_SIZE
#define FAT_SCRIPT_SIZE 4096
#endif
#ifndef USE_SCRIPT_FATFS_EXT
#define USE_SCRIPT_FATFS_EXT
#endif
#ifndef SDCARD_DIR
#define SDCARD_DIR
#endif

After flashing the tasmota.bin. The WEMOS D1 mini is starting and anything seems to be work, but it is not possible to configure the device. Which means all the settings you do e.g. Port configuration will get lost after the restart is done which is triggered by the SAVE command.

If I flash the same Tasmot.bin directly out of Visual Studio Code the SW runs and I can save the configs and they will be there after restart.

I asume, that maybe Tasmotizer 1.1c did not flash all the blocks which are needed with configuration of 4MB flash size.

**Comment by Jason2866** [comment]
All version compiled with not the 1M linker script are not supported. Tasmotizer is designed to flash supported build variants only.
