### ISSUE TITLE
Crashes and exits if connection isn't right

### ISSUE THREAD

**Issue by ChrisRomp** [tasmota/tasmotizer#54]
A couple of times I've had a not-perfect connection to the device, and Tasmotizer just crashes instead of showing an error or anything.

Windows 10 2004 build 19041.388.

**Comment by Jason2866** [comment]
New build ready for testing https://github.com/tasmota/tasmotizer/tree/1.1d
Just some minor polish missing ...

**Comment by Jason2866** [comment]
Fixed with release v.1.2
