### ISSUE TITLE
invalid syntax error running fresh tasmotizer download

### ISSUE THREAD

**Issue by wb666greene** [tasmota/tasmotizer#56]
Downloaded repo as a zip, minutes ago.

Installed requirements:
~/tasmotizer-release$ pip3 install -r requirements.txt
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyserial in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (3.4)
Requirement already satisfied: PyQt5>=5.10 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (5.15.1)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib/python3.5/dist-packages (from PyQt5>=5.10->-r requirements.txt (line 2)) (12.8.1)

Tried to get started:
~/tasmotizer-release$ python3 tasmotizer.py
  File "tasmotizer.py", line 380
    backup_size = f'0x{2 ** self.backup_size}00000'
                                                  ^
SyntaxError: invalid syntax

What is going on here?

**Comment by jziolkowski** [comment]
Python 3.5 that you are using doesn't support f-strings. Update python to at least 3.6. This is the reason why (if you tried) you weren't able to instal via `pip`
