### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by ShayBox** [tasmota/tasmotizer#57]
Without an explicit license, this project is "All rights reserved"

**Comment by jziolkowski** [comment]
Indeed I've overlooked that detail :) License file created.

Thanks for pointing it out.

**Comment by ShayBox** [comment]
I created an [AUR package](https://aur.archlinux.org/packages/tasmotizer-git/) for anyone that wants to use it on archlinux/manjaro

**Comment by jziolkowski** [comment]
Nice!
