### ISSUE TITLE
No module named 'tasmotizer_esptool'

### ISSUE THREAD

**Issue by robin13** [tasmota/tasmotizer#6]
I installed with `sudo pip3 install tasmotizer ` and then ran:

```
➜ ~ tasmotizer.py                            
Traceback (most recent call last):
  File "/usr/local/bin/tasmotizer.py", line 7, in <module>
    import tasmotizer_esptool as esptool
ModuleNotFoundError: No module named 'tasmotizer_esptool'
```

**Comment by jziolkowski** [comment]
Dang, wrong dash :D I'll send a new package to pypi, give me a few minutes.

**Comment by jziolkowski** [comment]
Uploaded tasmotizer 1.1.1 to pypi, the index should rebuild in a few minutes

**Comment by jziolkowski** [comment]
@Jason2866 no need to rebuild anything.

**Comment by jeylites** [comment]
I'm having the same problem.  

Apple Mac Osx 10.15.7 Catalina

```
 File "/usr/local/bin/tasmotizer.py", line 7, in <module>
    import tasmotizer_esptool as esptool
```

**Comment by jeylites** [comment]
Just updated Tasmotizer, seem to be working now.

**Comment by dangerweenie** [comment]
just installed on ubuntu, having the same issue:

ModuleNotFoundError: No module named 'tasmotizer_esptool'
