### ISSUE TITLE
Installation hurdles

### ISSUE THREAD

**Issue by mintgroen** [tasmota/tasmotizer#61]
After a lot of tinkering with the pip install, I managed to get that part successfully done.

Now running tasmotizer.py gives this error:

`pi@raspberrypi:~/tasmotizer $ tasmotizer.py 
Traceback (most recent call last):
  File "/usr/local/bin/tasmotizer.py", line 16, in <module>
    from PyQt5.QtSerialPort import QSerialPortInfo, QSerialPort
ValueError: PyCapsule_GetPointer called with incorrect name
`
Linux raspberrypi 5.4.70-v7l+ #1348 SMP 

On which I cannot find any tasmotizer related fixes on the great www, anyone an idea what is missing/incorrect on my machine?

**Comment by Jason2866** [comment]
RasPi is know to have problems with the installed QT5. See https://github.com/tasmota/tasmotizer/issues/26#issuecomment-671736372
