### ISSUE TITLE
Flash only works if Backup: Save original firmware option is disabled

### ISSUE THREAD

**Issue by bakoontz** [tasmota/tasmotizer#64]
I am flashing a couple of Sonoff basic switches, RF R2 v1.0 per the instructions on the tasmota.github.io site, using the x86 binary in Windows 7.  I am using an Arduino UNO for the USB to TTY conversion per these instructions:

https://siytek.com/how-to-flash-sonoff-tasmota-with-an-arduino-uno-and-esptool/

The update consistently failed when Backup: Save original firmware was selected (along with Release and Erase), usually with byte errors.  Disabling Backup allows the flash update to progress normally.

Downloading the firmware isn't really that important to me, I'm very pleased with the new firmware.  I just thought you all might want to know.

**Comment by jziolkowski** [comment]
Which version has this issue?
Also, you don't have to download the firmware each time as you can select a BIN file from your PC

I don't really follow what's the issue there

**Comment by bakoontz** [comment]
See attached image.  This option, when enabled, causes the session to fail.  When it's disabled, all works well.

![tasmota](https://user-images.githubusercontent.com/6192828/98835425-052a6400-2406-11eb-84be-2df2d2c42cdf.png)

**Comment by jziolkowski** [comment]
Do you power cycle the device after backup?

**Comment by bakoontz** [comment]
Never gets that far, the backup fails almost immediately, usually with byte mismatch errors.  Disabling the backup option does allow the flash to continue to completion.

**Comment by jziolkowski** [comment]
Interesting. Can you make a video of the process? Or at least post a screenshot of the error? Preferably the console output as well (run it inside cmd.exe)

**Comment by Jason2866** [comment]
Ouuch. Very bad idea to use a device with 5V logic levels.
It is just **WRONG** that the ESP8266 has GPIOs which are 5V tolerant.
Weird things can happen when the ESP8266 is tortured with 5V. You encountered one of.
Using the recommended USB serial adapter for flashing a ESpxxxx will result in a successfull flash.
It is just that easy. Case closed.

**Comment by jziolkowski** [comment]
Dang indeed. When reading the original issue somehow I omitted it's an UNO and assumed you are using the 3v3 version.
Then Jason is correct, this issue is not related to Tasmotizer.

**Comment by bakoontz** [comment]
That's why I mentioned it in my initial writeup.  There is ample evidence that ESP GPIOs are 5V-tolerant.  But it's whatever, still happy with the Tasmotizer.

**Comment by jziolkowski** [comment]
If it were, then your little setup would work. ;)

**Comment by bakoontz** [comment]
It works great actually.  I don't need Sonos' crappy firmware.  But yes, a proper USB-to-TTL adapter is a good suggestion.

**Comment by bakoontz** [comment]
@Jason2866 @jziolkowski Using a proper USB-to-TTL converter did the trick.  Thanks!

**Comment by beef-techau** [comment]
> Ouuch. Very bad idea to use a device with 5V logic levels.
> It is just **WRONG** that the ESP8266 has GPIOs which are 5V tolerant.
> Weird things can happen when the ESP8266 is tortured with 5V. You encountered one of.
> Using the recommended USB serial adapter for flashing a ESpxxxx will result in a successfull flash.
> It is just that easy. Case closed.

I’m having the same issue using 3.3v;
I’ve flashed ~12 or so devices and not been able to back up original firmware on; I’m using a PL2302 USB to TTL.

**Comment by bakoontz** [comment]
There’s a timing issue involved: Try starting your download IMMEDIATELY
after applying power. It took a couple tries for me to get it to work.

**Comment by beef-techau** [comment]
Thanks mate, will do

**Comment by Jason2866** [comment]
We do recommend for a worry free flashing "the golden CH340" https://tasmota.github.io/docs/Getting-Started/#needed-hardware

**Comment by jziolkowski** [comment]
as Jason said, plus ESP chips from one batch can be more/less susceptible to quality of USB adapters. CH340G is the recommended variant in regards to power supply, operational stability and stuff like that. Myself I have a PL2302 as well and it gives mixed results, whereas CH340G has a 100% success rate.

**Comment by beef-techau** [comment]
You’ll both be please to know that I have got one on the way. I couldn’t source one locally so it’s on the slow SS AliExpress
I’m just not sure what the deal with the jumper between 3.3v and tx in the pictures is for but I will sort it out when (if) it arrives 
![016252B8-302B-43F1-A3B4-FF972B15A68D](https://user-images.githubusercontent.com/61365310/101269163-605a3700-37b7-11eb-8c49-59f4deb708eb.png)

**Comment by Jason2866** [comment]
The jumper placing is just for parking the jumper. Please remove and place it on the 5V pin.
Doing this it prevents you to accidently connect the 5v rail to the esp
