### ISSUE TITLE
Tasmotizer do not start on macOS Big Sur 

### ISSUE THREAD

**Issue by typepub** [tasmota/tasmotizer#65]
Hello,

Facing a problem on a fresh install of Tasmotizer:
python3 -m venv venv2
. venv2/bin/activate 
pip install tasmotizer
Successfully installed PyQt5-5.15.1 PyQt5-sip-12.8.1 pyserial-3.4 tasmotizer-1.2.1

When starting Tasmotizer, no window appear and Python is stuck 100% of CPU. Have to kill it. Tried to wait for 5 minutes but no window appear and still stuck.

Any idea of what I can try please?

Thanks.

**Comment by jimmyhall82** [comment]
I am having the same issue, did you manage to solve this yet?

**Comment by typepub** [comment]
No solution found. I used a workaround: https://tasmota.github.io/docs/Getting-Started/#esptoolpy

**Comment by grobian19** [comment]
Same problem here

**Comment by ghkuf** [comment]
same here

**Comment by Jason2866** [comment]
Use latest pyserial for Big Sur see https://github.com/pyserial/pyserial/issues/509#issuecomment-726966076
Short `pip3 install pyserial --pre --force`

**Comment by apastuszak** [comment]
The latest pyserial does not fix the issue.  Can we reopen this?

**Comment by yuriy-logosha** [comment]
Working on Python3.8, but doesn't with 3.9
Big Sur 11.5
