### ISSUE TITLE
Would some one  please tell us non-Programmers were the backup .bins are kept can Details be that be put in plain sight 

### ISSUE THREAD

**Issue by mutantxxxx** [tasmota/tasmotizer#66]
Would some tell us non-Programmers were the backup .bins are kept can that be put in plain sight 
You mention backs made before flashing which it did
But were??? the are they were???  is the default place what are the default names ???
I could see that it was backing up but spent hour and gave up trying to find the backups when I wanted flash back original image .
So easy to do the authors put WERE THESE backup images wopuls saved ????
Yes I know we all have lots of time at present but doing full scans of c: drive 
to locate backup files  oohh dear come on gentalmen please a bit more info please . for non-programmers

**Comment by ascillato** [comment]
Hi,

It is stored as _backup_date_time.bin_ (like _backup_20201121_203138.bin_) in **the same folder** where you have put **_tasmotizer-1.2.exe_**

If you have the file **_tasmotizer-1.2.exe_** in your desktop, your backup file will be there too.

_( Remember that when doing the backup, you MUST match the real amount of flash memory of the device. For example a sonoff basic has 1MB flash, a Shelly 1 has 2MB flash, etc. Wrong memory selection will make an unusable backup )_

**Comment by dartrax** [comment]
In my case, the files are not saved where the tasmotizer.exe is.
It get's saved in the folder of that exe that starts the tasmotizer.exe-process. That's a little bit annoying, but I admit that is a special case not common to everyone.

**Comment by jziolkowski** [comment]
Sorry, but I don't get the difference between where tasmotizer is and the other location you mentioned

**Comment by dartrax** [comment]
Thanks for the replay!
Tasmotizer is here:
D:\Projects\TASMOTA\Tasmotizer\tasmotizer-1.2.exe
The backups are saved here:
D:\Drive\OrderManager\bin\Debug\

**Comment by jziolkowski** [comment]
ahhh ok now I get it.
Then you are correct. The bins are saved in the _working_ directory, not exactly the same where tasmotizer.exe is

**Comment by mac-city** [comment]
what about us mac users?  can't find my backup anywhere :-(  plus it is crashing the gui after backup but I am hoping the backup completed somewhere so I can try to restore my sonoff to original firmware.
