### ISSUE TITLE
Needs improvements

### ISSUE THREAD

**Issue by mkh595** [tasmota/tasmotizer#7]
It looks that this is easy tool to flash firmware and not need to deal with long command line or addresses where to put which file (ESP8266flasher).

But program needs improvements to avoid crashes (tested windows version)

- when selected port is already open e.g. in serial monitor, program crash. It should say that serial port cannot be open and allow to select another port or start flash again after port is closed

I tested with Wemos D1 mini

- own selected bin file was uploaded correctly

- upload release option ended with error

![tasmotizer1](https://user-images.githubusercontent.com/30566575/70860724-9a3a8980-1f25-11ea-8604-20b8985fb15c.JPG)

- after previous error I am not able to flash back neither my own file. 

![tasmotizer2](https://user-images.githubusercontent.com/30566575/70860766-3e243500-1f26-11ea-86b4-c3de29360438.JPG)

- after sucessfull flash device cannot be flashed again until is physically disconnected. Same error like above

- when button OK is pressed it crash instead of stay open

Edit: Device had to be disconnected to flash it again but program didn't start. Now it cannot be flashed anymore. If I try flask from Visual Studio code I get this error:

```
Building .pioenvs\sonoff\firmware.bin
Checking size .pioenvs\sonoff\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
DATA:    [=======   ]  65.8% (used 53920 bytes from 81920 bytes)
PROGRAM: [=====     ]  47.2% (used 494499 bytes from 1048576 bytes)
Configuring upload protocol...
Looking for upload port...
Auto-detected: COM24
Uploading .pioenvs\sonoff\firmware.bin
Uploading 498640 bytes from .pioenvs\sonoff\firmware.bin to flash at 0x00000000
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_BEGIN) failed
error: espcomm_upload_mem failed
*** [upload] Error -1 
```
Looks that device is dead. Thank you.

**Comment by jziolkowski** [comment]
It's not possible to kill a device by a bad flash. As for the remaining issues I'll have a look.

**Comment by jziolkowski** [comment]
The device can't be programmed again after flashing because Tasmotizer stick to the default esptool behavior of resetting the device after flashing, ergo triggering a normal boot. I'll add that as an option for the user in the next release, including the check if the port is already claimed.

As for the reasons of why other software is also unable to flash your device: there can be a myriad reasons, starting with the faulty device, faulty flash, faulty adapter etc etc, so I can't really tell anything there.

**Comment by jziolkowski** [comment]
Closing due to lack of feedback.
