### ISSUE TITLE
Flashed a Tuya board - how to restore the backup?

### ISSUE THREAD

**Issue by gooman-uk** [tasmota/tasmotizer#74]
I have a glass flat panel heater that uses a TYWE1S on a TYJW2S-5V board, which I flashed with the latest release of Tasmota, but unfortunately the MCU uses a non-standard comms protocol and so can't be (easily) controlled from Tasmota.

I took a backup of the stock firmware using Tasmotizer. I've tried reflashing using that backup as the BIN file, but the device won't re-pair with the Tuya Smart Life app. Looks like something didn't get reloaded properly.

Any guesses on how to solve this?

Otherwise it looks like all I've succeeded in doing is turning my Smart heater into a dumb one ... :-(

**Comment by jziolkowski** [comment]
The original firmware might need a different flashing mode than is required with Tasmota, therefore to flash the original firmware you'll have more success with esptool directly. After all, Tasmotizer is to write tasmota firmware and uses the specific settings to achieve that.

The only thing that comes to mind is did you do the full erase before writing the backup to this unit? Maybe there are some tasmota leftovers.

Other than that, no idea. During testing the backup/rewrite functionality was tested on many devices and it worked. With that saId I'm aware this might not work in 100% situations.

And finally, many Tuya devices can be used with TuyaMCUs onboard using TuyaMCU command, so maybe give it a go?

Perhaps someone over at our Discord server would help in the hardware-talk channel
