### ISSUE TITLE
raspberry pi failing install

### ISSUE THREAD

**Issue by reedstlouis** [tasmota/tasmotizer#96]
I have updated to current release of OS and was able to install by method 2 and 3 but both fail to launch
File "/usr/local/bin/tasmotizer.py", Line 16, in <module>
 from PyQt5.QtSerialPort import QSerialPortInfo, QSerialPort
ModuleNotFoundError: No module named 'PyQt5.QtSerialPort'

I have tried all the solutions I could find but still will not start any ideals?

**Comment by Jason2866** [comment]
See #26
