### ISSUE TITLE
cannot load bin data error

### ISSUE THREAD

**Issue by MinaMalak-cmd** [tasmota/tasmotizer#99]
when I switched from 'BIN File' mode into 'release ' mode it gives me an error of  'cannot load bin data expecting value' as shown in image attached below

<img width="249" alt="Untitled" src="https://user-images.githubusercontent.com/59808870/115018967-d33b9300-9eb8-11eb-89a1-1a8c0329617f.png">

**Comment by jziolkowski** [comment]
Hmm, does the release button show the version next to it? I assume that it's connected to internet...

**Comment by MinaMalak-cmd** [comment]
@jziolkowski if i understand your question correctly, no it doesn't show any thing

**Comment by jziolkowski** [comment]
can you paste screenshots of the interface with 'release' and then 'development' clicked?

**Comment by MinaMalak-cmd** [comment]
I couldn't proceed to release every time i try it to click on development or release it gives me that error and stop on BIN file

**Comment by jziolkowski** [comment]
ahh got it. so perhaps it's an external issue with the JSON data with builds information. I'll check it.

**Comment by MinaMalak-cmd** [comment]
ok waiting for your checking, hope this happen soon

**Comment by ascillato** [comment]
I have just tested and works fine in my PC.

![image](https://user-images.githubusercontent.com/35405447/115021215-10405f00-9e92-11eb-9c99-388d2a95030b.png)

Do you have internet connection on that computer? or an active firewall?

**Comment by MinaMalak-cmd** [comment]
yes I have good internet connection, and disabled anti virus, is there any other thing to do to solve this problem?

**Comment by MinaMalak-cmd** [comment]
the problem has been solved it was due to antivirus

**Comment by ascillato** [comment]
@MinaMalak-cmd

Nice catch.

I could reproduce your error. It is given only when Tasmotizer can't access internet.

@jziolkowski 
Is it possible to change the error message to something like **_A Internet connection is required for this feature to work_** ?
